info:
    serviceLinks:
        metrics: "{metricsHostname}/dashboard/db/openshift-project-spring-actuator-view?var-ds=openshift-{cluster}-ose&var-namespace={namespace}&var-app={name}"
    podLinks:
        metrics: "{metricsHostname}/dashboard/db/openshift-project-spring-actuator-view-instance?var-ds=openshift-{cluster}-ose&var-namespace={namespace}&var-app={name}&var-instance={podName}"

spring:
    profiles:
        active: local

logging:
    level:
        no.skatteetaten.aurora.cantus: DEBUG
        org:
            hibernate: WARN
            springframework: INFO
            apache:
                catalina: WARN
                velocity: WARN

integrations:
    docker:
        cluster:
            url: docker-registry.default.svc:5000
            https: false
            auth: Bearer
            readOnly: true
            enabled: true
        old:
            url: docker-registry.aurora.sits.no:5000
            https: true
            auth: None
            readOnly: false
            enabled: true
        nexus-pull:
            url: container-registry-internal-private-pull.aurora.skead.no:443
            https: true
            auth: None
            readOnly: true
            enabled: true
        nexus-release:
            url: container-registry-internal-release.aurora.skead.no:443
            https: true
            auth: Basic
            readOnly: false

cantus.docker.internal.urls: "foo"
cantus.docker.urlsallowed: ""

---
spring:
    profiles: local

cantus:
    username: cantus
    password: cantus

server:
    port: 8080
    max-http-header-size: 200000

logging:
    pattern:
        console: "%d [%-9.9thread] %highlight(%-5level) %cyan(%logger:%L) %X - %msg %n%rEx{full}"
    # add mokey.openshift.token to ~/.spring-boot-devtools.properties

---
spring:
    profiles: openshift
